import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Snowfall from "react-snowfall";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Snow behind everything */}
        <Snowfall
          snowflakeCount={180}
          style={{
            position: "fixed", // stick to viewport
            top: 0,
            left: 0,
            width: "100vw",
            height: "100vh",
            pointerEvents: "none", // don't block clicks
            zIndex: 0, // low layer
          }}
        />

        {/* Your app content above */}
        <div style={{ position: "relative", zIndex: 1 }}>{children}</div>
      </body>
    </html>
  );
}
